# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-07 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0002_auto_20170905_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
