# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-27 08:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mlearn', '0003_leaderboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='user',
        ),
        migrations.AddField(
            model_name='competition',
            name='Comp_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='score',
            field=models.FloatField(),
        ),
    ]
