# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-03 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mlearn', '0004_auto_20170727_0954'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competition',
            old_name='Comp_id',
            new_name='comp_id',
        ),
    ]
