# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 06:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('mlearn', '0007_auto_20170819_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
