# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mlearn', '0008_auto_20170819_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='rank',
        ),
        migrations.AlterField(
            model_name='competition',
            name='test2',
            field=models.FileField(blank=True, default=b'', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='competition',
            name='train2',
            field=models.FileField(blank=True, default=b'', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='competition',
            name='valid',
            field=models.FileField(blank=True, default=b'', null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='algo',
            field=models.CharField(
                choices=[(b'Reg', b'Regression'), (b'LogReg', b'Logistic Regression'), (b'RandF', b'Random Forest'),
                         (b'KNN', b'K - Nearest Neighbour'), (b'NN', b'Neural Networks'),
                         (b'ACO', b'Ant Colony Optimization'), (b'SVM', b'Support Vector Machines'),
                         (b'PSA', b'Particle Swarm Algorithm'), (b'Oth', b'Other')], default=b'Reg', max_length=100),
        ),
    ]
