# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mlearn', '0009_auto_20170819_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='points',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='rank',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(default=b'', upload_to=b''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='f_name',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='l_name',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mail_id',
            field=models.EmailField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=b'', max_length=50),
        ),
    ]
