# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-22 17:32
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlearn', '0010_auto_20170819_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='submission',
            name='file_submission',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='competition',
            name='logo',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='competition',
            name='sample',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[('A', 'Active'), ('C', 'Closed')], default='Active', max_length=1),
        ),
        migrations.AlterField(
            model_name='competition',
            name='test',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='competition',
            name='test2',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='competition',
            name='train',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='competition',
            name='train2',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='competition',
            name='valid',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='path',
            field=models.FilePathField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='submission',
            name='algo',
            field=models.CharField(
                choices=[('Reg', 'Regression'), ('LogReg', 'Logistic Regression'), ('RandF', 'Random Forest'),
                         ('KNN', 'K - Nearest Neighbour'), ('NN', 'Neural Networks'),
                         ('ACO', 'Ant Colony Optimization'), ('SVM', 'Support Vector Machines'),
                         ('PSA', 'Particle Swarm Algorithm'), ('Oth', 'Other')], default='Reg', max_length=100),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(
                choices=[('Python', 'Python'), ('C', 'C'), ('C++', 'C++'), ('R', 'R'), ('Python3', 'Python3'),
                         ('Scala', 'Scala')], default='Python', max_length=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='f_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='l_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mail_id',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='registration',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlearn.Competition'),
        ),
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
