# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-04 17:40
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=1000)),
                ('logo', models.FileField(default='', upload_to='')),
                ('team_size', models.IntegerField(default=1)),
                (
                'status', models.CharField(choices=[('A', 'Active'), ('C', 'Closed')], default='Active', max_length=1)),
                ('start', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('sample', models.FileField(blank=True, default='', null=True, upload_to='')),
                ('train', models.FileField(default='', upload_to='')),
                ('test', models.FileField(default='', upload_to='')),
                ('train2', models.FileField(blank=True, default='', null=True, upload_to='')),
                ('test2', models.FileField(blank=True, default='', null=True, upload_to='')),
                ('valid', models.FileField(blank=True, default='', null=True, upload_to='')),
                ('gold', models.IntegerField(default=0)),
                ('silver', models.IntegerField(default=0)),
                ('bronze', models.IntegerField(default=0)),
                ('prize4', models.IntegerField(default=0)),
                ('prize5', models.IntegerField(default=0)),
                ('prize6', models.IntegerField(default=0)),
                ('prize7', models.IntegerField(default=0)),
                ('prize8', models.IntegerField(default=0)),
                ('prize9', models.IntegerField(default=0)),
                ('prize10', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp.Competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_submission', models.FileField(default='', upload_to='')),
                ('time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=64)),
                ('language', models.CharField(
                    choices=[('Python', 'Python'), ('C', 'C'), ('C++', 'C++'), ('R', 'R'), ('Python3', 'Python3'),
                             ('Scala', 'Scala')], default='Python', max_length=100)),
                ('algo', models.CharField(
                    choices=[('Reg', 'Regression'), ('LogReg', 'Logistic Regression'), ('RandF', 'Random Forest'),
                             ('KNN', 'K - Nearest Neighbour'), ('NN', 'Neural Networks'),
                             ('ACO', 'Ant Colony Optimization'), ('SVM', 'Support Vector Machines'),
                             ('PSA', 'Particle Swarm Algorithm'), ('Oth', 'Other')], default='Reg', max_length=100)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comp.Competition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
