# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-25 10:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlearn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=50)),
                ('comp_desc', models.CharField(max_length=1000)),
                ('comp_logo', models.FileField(default=b'', upload_to=b'')),
                ('comp_train', models.FileField(default=b'', upload_to=b'')),
                ('comp_test', models.FileField(default=b'', upload_to=b'')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
                                           to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
