# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-08-26 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='competition',
            name='sample',
            field=models.FileField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
