# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-05 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='desc',
            field=models.TextField(max_length=5000),
        ),
    ]
