# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-07 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comp', '0003_auto_20170907_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=64),
        ),
    ]
