# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-07 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comp', '0004_auto_20170907_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='scoring_formula',
            field=models.CharField(choices=[('Inv RMSE', 'Inverse RMSE'), ('DIff', 'Simple Difference')], default='',
                                   max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='sample',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='competition',
            name='valid',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=64),
        ),
    ]
