# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 06:27
from __future__ import unicode_literals

import datetime

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mlearn', '0005_auto_20170803_1253'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('rank', models.IntegerField(default=9999)),
                ('language', models.CharField(
                    choices=[(b'Python', b'Python'), (b'C', b'C'), (b'C++', b'C++'), (b'R', b'R'),
                             (b'Python3', b'Python3'), (b'Scala', b'Scala')], default=b'Python', max_length=1)),
                ('algo', models.CharField(
                    choices=[(b'Reg', b'Regression'), (b'LogReg', b'Logistic Regression'), (b'RandF', b'Random Forest'),
                             (b'KNN', b'K - Nearest Neighbour'), (b'NN', b'Neural Networks'),
                             (b'ACO', b'Ant Colony Optimization'), (b'SVM', b'Support Vector Machines'),
                             (b'PSA', b'Particle Swarm Algorithm')], default=b'Reg', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_id', models.EmailField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('rank', models.IntegerField(default=9999)),
                ('points', models.DecimalField(decimal_places=2, max_digits=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='leaderboard',
            name='user',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='comp_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='comp_logo',
            new_name='logo',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='comp_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='comp_test',
            new_name='sample',
        ),
        migrations.RenameField(
            model_name='competition',
            old_name='comp_train',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='data_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='file_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='file_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='comp_id',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='file_path',
        ),
        migrations.AddField(
            model_name='competition',
            name='bronze',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='prize10',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='prize4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='prize5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='prize6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='prize7',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='prize8',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='prize9',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='silver',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='competition',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='competition',
            name='status',
            field=models.CharField(choices=[(b'A', b'Active'), (b'C', b'Closed')], default=b'Active', max_length=1),
        ),
        migrations.AddField(
            model_name='competition',
            name='team_size',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='competition',
            name='test2',
            field=models.FileField(default=b'', upload_to=b''),
        ),
        migrations.AddField(
            model_name='competition',
            name='train',
            field=models.FileField(default=b'', upload_to=b''),
        ),
        migrations.AddField(
            model_name='competition',
            name='train2',
            field=models.FileField(default=b'', upload_to=b''),
        ),
        migrations.AddField(
            model_name='competition',
            name='valid',
            field=models.FileField(default=b'', upload_to=b''),
        ),
        migrations.AddField(
            model_name='dataset',
            name='path',
            field=models.FilePathField(default=b'', max_length=500),
        ),
        migrations.AlterField(
            model_name='competition',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.AddField(
            model_name='submission',
            name='comp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlearn.Competition'),
        ),
        migrations.AddField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mlearn.Team'),
        ),
    ]
