# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-07 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comp', '0006_auto_20170908_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='scoring_formula',
            field=models.CharField(choices=[('Inv RMSE', 'Inverse RMSE'), ('DIff', 'Simple Difference')],
                                   default='Inv RMSE', max_length=50),
        ),
    ]
