# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-19 06:29
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mlearn', '0006_auto_20170819_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
