# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-09-07 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('comp', '0007_auto_20170908_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=64),
        ),
    ]
